#!/usr/bin/env python

import sys
from datetime import datetime
import os

arg = sys.argv[1]
now = datetime.now()
job_file = open(
    os.path.join(
        "/home/ryott/.config/timecard",
        "timeCard_{}.log".format(arg)
    ),
    "a",
)
job_file.write("Clocked In: {}\n".format(now.strftime("%Y-%m-%d %H:%M:%S")))
job_file.close()

print(f"You have clocked in for {arg}!")